### ISSUE TITLE
30/12

### ISSUE THREAD

**Issue by MichielBontenbal** [MichielBbal/snoring_sound_sensor#1]
[{'measurement': 'my_snoring', 'fields': {'sheets': 0.0011662334436550736, 'silence': 0.9374314546585083, 'snoring': 0.06139537692070007, 'softtalking': 6.8787758209509775e-06}}]
[{'measurement': 'my_snoring', 'fields': {'sheets': 0.0012563932687044144, 'silence': 0.935369610786438, 'snoring': 0.06336664408445358, 'softtalking': 7.339086550928187e-06}}]
[{'measurement': 'my_snoring', 'fields': {'sheets': 0.0012975154677405953, 'silence': 0.9332032799720764, 'snoring': 0.06549125909805298, 'softtalking': 8.023716873140074e-06}}]
[{'measurement': 'my_snoring', 'fields': {'sheets': 0.0018337176879867911, 'silence': 0.9296778440475464, 'snoring': 0.06847682595252991, 'softtalking': 1.150548632722348e-05}}]
[{'measurement': 'my_snoring', 'fields': {'sheets': 0.002023717388510704, 'silence': 0.9243278503417969, 'snoring': 0.07363588362932205, 'softtalking': 1.2543928278319072e-05}}]ALSA lib pcm.c:8424:(snd_pcm_recover) overrun occurred
ALSA lib pcm.c:8427:(snd_pcm_recover) cannot recovery from overrun, prepare failed: Input/output error
Expression 'alsa_snd_pcm_prepare( stream->capture.pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2932
Expression 'AlsaStart( stream, 0 )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3246
Expression 'AlsaRestart( self )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3313
Expression 'PaAlsaStream_HandleXrun( self )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4182
Expression 'PaAlsaStream_SetUpBuffers( stream, &framesGot, &xrun )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4355

[{'measurement': 'my_snoring', 'fields': {'sheets': 0.0023620487190783024, 'silence': 0.9148474931716919, 'snoring': 0.08277583122253418, 'softtalking': 1.4631918929808307e-05}}]
[{'measurement': 'my_snoring', 'fields': {'sheets': 0.0019335357937961817, 'silence': 0.9263314008712769, 'snoring': 0.07172263413667679, 'softtalking': 1.2531713764474262e-05}}]
Traceback (most recent call last):
  File "sound_classifier.py", line 88, in <module>
    main(sys.argv[1:])
  File "sound_classifier.py", line 78, in main
    client.write_points(json_body)
  File "/home/pi/.local/lib/python3.7/site-packages/influxdb/client.py", line 608, in write_points
    consistency=consistency)
  File "/home/pi/.local/lib/python3.7/site-packages/influxdb/client.py", line 685, in _write_points
    protocol=protocol
  File "/home/pi/.local/lib/python3.7/site-packages/influxdb/client.py", line 419, in write
    headers=headers
  File "/home/pi/.local/lib/python3.7/site-packages/influxdb/client.py", line 373, in request
    raise InfluxDBServerError(reformat_error(response))
influxdb.exceptions.InfluxDBServerError: {"error":"timeout"}

**Comment by MichielBontenbal** [comment]
2 januari: 
[{'measurement': 'my_snoring', 'fields': {'sheets': 0.0008588085183873773, 'silence': 0.9312624335289001, 'snoring': 0.06787433475255966, 'softtalking': 4.407494088809472e-06}}]
[{'measurement': 'my_snoring', 'fields': {'sheets': 0.0006641817162744701, 'silence': 0.9349494576454163, 'snoring': 0.06438222527503967, 'softtalking': 4.153992904321058e-06}}]
[{'measurement': 'my_snoring', 'fields': {'sheets': 0.000999976764433086, 'silence': 0.9391530752182007, 'snoring': 0.05984153598546982, 'softtalking': 5.516866167454282e-06}}]
Traceback (most recent call last):
  File "sound_classifier.py", line 88, in <module>
    main(sys.argv[1:])
  File "sound_classifier.py", line 78, in main
    client.write_points(json_body)
  File "/home/pi/.local/lib/python3.7/site-packages/influxdb/client.py", line 608, in write_points
    consistency=consistency)
  File "/home/pi/.local/lib/python3.7/site-packages/influxdb/client.py", line 685, in _write_points
    protocol=protocol
  File "/home/pi/.local/lib/python3.7/site-packages/influxdb/client.py", line 419, in write
    headers=headers
  File "/home/pi/.local/lib/python3.7/site-packages/influxdb/client.py", line 373, in request
    raise InfluxDBServerError(reformat_error(response))
influxdb.exceptions.InfluxDBServerError: {"error":"timeout"}
