### ISSUE TITLE
12/01

### ISSUE THREAD

**Issue by MichielBontenbal** [MichielBbal/snoring_sound_sensor#2]
With Raspi 4, script started from ssh ubuntu.

[{'measurement': 'my_snoring', 'fields': {'sheets': 9.624481123182704e-08, 'silence': 0.12692385911941528, 'snoring': 0.8730654716491699, 'softtalking': 1.0547596502874512e-05}}]
[{'measurement': 'my_snoring', 'fields': {'sheets': 2.8842305255238898e-05, 'silence': 0.9245078563690186, 'snoring': 0.07546037435531616, 'softtalking': 2.948858764284523e-06}}]
Traceback (most recent call last):
  File "sound_classifier.py", line 88, in <module>
    main(sys.argv[1:])
  File "sound_classifier.py", line 64, in main
    for res, audio in runner.classifier(device_id=selected_device_id):
  File "/home/pi/.local/lib/python3.7/site-packages/edge_impulse_linux/audio.py", line 159, in classifier
    for audio in generator:
  File "/home/pi/.local/lib/python3.7/site-packages/edge_impulse_linux/audio.py", line 123, in generator
    yield b''.join(data)
MemoryError

**Comment by MichielBontenbal** [comment]
Did i call home assistant at same time?
[{'measurement': 'my_snoring', 'fields': {'sheets': 0.0020020294468849897, 'silence': 0.9318625330924988, 'snoring': 0.06612241268157959, 'softtalking': 1.3008427231397945e-05}}]
[{'measurement': 'my_snoring', 'fields': {'sheets': 0.002000450389459729, 'silence': 0.9317987561225891, 'snoring': 0.06618775427341461, 'softtalking': 1.2982936823391356e-05}}]
[{'measurement': 'my_snoring', 'fields': {'sheets': 0.0019282771972939372, 'silence': 0.9332987070083618, 'snoring': 0.06476053595542908, 'softtalking': 1.247456566488836e-05}}]
Traceback (most recent call last):
  File "sound_classifier.py", line 88, in <module>
    main(sys.argv[1:])
  File "sound_classifier.py", line 64, in main
    for res, audio in runner.classifier(device_id=selected_device_id):
  File "/home/pi/.local/lib/python3.7/site-packages/edge_impulse_linux/audio.py", line 161, in classifier
    features = np.concatenate((features, data), axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
numpy.core._exceptions.MemoryError: Unable to allocate 679. MiB for an array with shape (356084608,) and data type int16
